---
- hosts: all
  become: true
  tasks:
    - name: Install docker
      apt:
        name: docker
        update_cache: yes
        state: present
    - name: Install docker-compose
      apt:
        name: docker-compose
        state: present
    - name: Add ubuntu user to the docker group
      user:
        name: ubuntu
        groups: docker
    - name: Copy docker stuffs
      copy:
        src: ../docker
        dest: /opt
        owner: ubuntu
        group: docker
